from django.contrib import admin
from .models import *


admin.site.register(PPICogScore)
admin.site.register(COGMethodScore)
admin.site.register(COGInteractionSource)
admin.site.register(COGSourceInformation)
admin.site.register(COGInterationPair)
admin.site.register(SourceCog)
admin.site.register(ProteinCog)
admin.site.register(COG)
admin.site.register(Family)
admin.site.register(Genus)
admin.site.register(Specie)
admin.site.register(Strain)
admin.site.register(SourceData)
admin.site.register(BaltimoreClassification)
admin.site.register(PersonResponsible)
admin.site.register(Bacterium)
admin.site.register(Bacteriophage)
admin.site.register(Gene)
admin.site.register(Contig)
admin.site.register(Protein)
admin.site.register(InteractionValidity)
admin.site.register(LevelInteraction)
admin.site.register(LysisType)
admin.site.register(Couple)
admin.site.register(DomainInteractionScore)
admin.site.register(DomainMethodScore)
admin.site.register(Domain)
admin.site.register(DomainInterationsPair)
admin.site.register(DomainSourceInformation)
admin.site.register(DomainInteractionSource)
admin.site.register(SourcePFAM)
admin.site.register(ProteinPfam)
admin.site.register(PFAMMethodScore)
admin.site.register(PPISource)
admin.site.register(PPI)
admin.site.register(PPIInteractionSource)
admin.site.register(PPIPFAMScore)
admin.site.register(WholeDNA)

# Register your models here.
