# Generated by Django 2.1.1 on 2018-09-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inphinity_orm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='families',
            name='designation_fa',
            field=models.TextField(unique=True),
        ),
    ]
