# Generated by Django 2.1.1 on 2018-09-26 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inphinity_orm', '0002_auto_20180926_1128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Families',
            new_name='Family',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='designation_fa',
            new_name='designation',
        ),
    ]
