# Generated by Django 2.1.1 on 2018-09-26 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inphinity_orm', '0005_specie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specie',
            name='genus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inphinity_orm.Genus'),
        ),
    ]
