# Generated by Django 2.1.1 on 2018-09-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inphinity_orm', '0007_sourcedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaltimoreClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField(unique=True)),
                ('designation', models.TextField(unique=True)),
            ],
        ),
    ]
