# Generated by Django 2.1.1 on 2018-09-27 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inphinity_orm', '0009_personresponsible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_number', models.TextField(max_length=20, null=True, unique=True)),
                ('gi_number', models.TextField(max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField(unique=True)),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inphinity_orm.Specie')),
            ],
        ),
        migrations.CreateModel(
            name='Bacteriophage',
            fields=[
                ('organism_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inphinity_orm.Organism')),
                ('designation', models.TextField(unique=True)),
                ('baltimore_classification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inphinity_orm.BaltimoreClassification')),
            ],
            bases=('inphinity_orm.organism',),
        ),
        migrations.CreateModel(
            name='Bacterium',
            fields=[
                ('organism_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inphinity_orm.Organism')),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inphinity_orm.Strain')),
            ],
            bases=('inphinity_orm.organism',),
        ),
        migrations.AddField(
            model_name='organism',
            name='person_responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inphinity_orm.PersonResponsible'),
        ),
        migrations.AddField(
            model_name='organism',
            name='source_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inphinity_orm.SourceData'),
        ),
    ]
