# Generated by Django 2.1.1 on 2018-09-27 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inphinity_orm', '0010_auto_20180927_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_db_online', models.TextField(null=True)),
                ('sequence_DNA', models.TextField()),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inphinity_orm.Organism')),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_db_online', models.TextField(null=True)),
                ('sequence_DNA', models.TextField()),
                ('fasta_head', models.TextField(null=True)),
                ('position_start', models.PositiveIntegerField(null=True)),
                ('position_end', models.PositiveIntegerField(null=True)),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inphinity_orm.Organism')),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_db_online', models.TextField(null=True)),
                ('sequence_AA', models.TextField()),
                ('fasta_head', models.TextField(null=True)),
                ('position_start', models.PositiveIntegerField(null=True)),
                ('position_end', models.PositiveIntegerField(null=True)),
                ('position_start_contig', models.PositiveIntegerField(null=True)),
                ('position_end_contig', models.PositiveIntegerField(null=True)),
                ('contig', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inphinity_orm.Contig')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inphinity_orm.Gene')),
            ],
        ),
    ]
