# Generated by Django 2.1.1 on 2018-09-27 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inphinity_orm', '0011_contig_gene_protein'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.BooleanField()),
                ('bacteriophage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inphinity_orm.Bacteriophage')),
                ('bacterium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inphinity_orm.Bacterium')),
            ],
        ),
        migrations.CreateModel(
            name='InteractionValidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LevelInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LysisType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='couple',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inphinity_orm.LevelInteraction'),
        ),
        migrations.AddField(
            model_name='couple',
            name='lysis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inphinity_orm.LysisType'),
        ),
        migrations.AddField(
            model_name='couple',
            name='person_responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inphinity_orm.PersonResponsible'),
        ),
        migrations.AddField(
            model_name='couple',
            name='source_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inphinity_orm.SourceData'),
        ),
        migrations.AddField(
            model_name='couple',
            name='validity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inphinity_orm.InteractionValidity'),
        ),
    ]
