# Generated by Django 2.1.1 on 2018-09-27 12:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inphinity_orm', '0012_auto_20180927_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DomainInteractionSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DomainInterationsPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DomainInterationsPair_domainA', to='inphinity_orm.Domain')),
                ('domain_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DomainInterationsPair_domainB', to='inphinity_orm.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='DomainSourceInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField(unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='couple',
            unique_together={('bacterium', 'bacteriophage')},
        ),
        migrations.AddField(
            model_name='domaininteractionsource',
            name='domain_interaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inphinity_orm.DomainInterationsPair'),
        ),
        migrations.AddField(
            model_name='domaininteractionsource',
            name='information_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inphinity_orm.DomainSourceInformation'),
        ),
        migrations.AlterUniqueTogether(
            name='domaininterationspair',
            unique_together={('domain_a', 'domain_b')},
        ),
    ]
