# Generated by Django 2.1.1 on 2018-09-27 12:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inphinity_orm', '0013_auto_20180927_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinsPfams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(default=django.utils.timezone.now)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inphinity_orm.Domain')),
                ('person_responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inphinity_orm.PersonResponsible')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inphinity_orm.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='SourcePFAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='proteinspfams',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inphinity_orm.SourcePFAM'),
        ),
    ]
