# Generated by Django 2.1.1 on 2018-09-27 13:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inphinity_orm', '0014_auto_20180927_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(default=django.utils.timezone.now)),
                ('protein_bacterium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PPI_bacterium', to='inphinity_orm.Protein')),
                ('protein_bacterophage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PPI_bacteriophage', to='inphinity_orm.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='PPIMethodScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PPIScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('date_creation', models.DateField(default=django.utils.timezone.now)),
                ('ppi_interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inphinity_orm.PPI')),
                ('ppi_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inphinity_orm.PPIMethodScore')),
            ],
        ),
        migrations.CreateModel(
            name='PPISource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ppi',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inphinity_orm.PPISource'),
        ),
    ]
