# Generated by Django 2.1.1 on 2018-09-27 13:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inphinity_orm', '0015_auto_20180927_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='COGS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='COGSInteractionSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='COGSInterationsPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cog_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='COGSInterationsPair_domainA', to='inphinity_orm.COGS')),
                ('cog_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='COGSInterationsPair_domainB', to='inphinity_orm.COGS')),
            ],
        ),
        migrations.CreateModel(
            name='COGSSourceInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PPIInteractionSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='ppi',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='ppi',
            name='source',
        ),
        migrations.AlterUniqueTogether(
            name='ppi',
            unique_together={('protein_bacterium', 'protein_bacterophage')},
        ),
        migrations.AddField(
            model_name='ppiinteractionsource',
            name='ppi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inphinity_orm.PPI'),
        ),
        migrations.AddField(
            model_name='ppiinteractionsource',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inphinity_orm.PPISource'),
        ),
        migrations.AddField(
            model_name='cogsinteractionsource',
            name='cogs_interaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inphinity_orm.COGSInterationsPair'),
        ),
        migrations.AddField(
            model_name='cogsinteractionsource',
            name='information_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inphinity_orm.COGSSourceInformation'),
        ),
        migrations.AlterUniqueTogether(
            name='cogsinterationspair',
            unique_together={('cog_a', 'cog_b')},
        ),
    ]
