# Generated by Django 2.1.1 on 2018-10-11 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inphinity_orm', '0019_auto_20181011_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='person_responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_responsible', to='inphinity_orm.PersonResponsible'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='source_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_data', to='inphinity_orm.SourceData'),
        ),
        migrations.AlterField(
            model_name='strain',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strains', to='inphinity_orm.Specie'),
        ),
        migrations.AlterUniqueTogether(
            name='strain',
            unique_together={('specie', 'designation')},
        ),
    ]
