# Generated by Django 2.1.1 on 2018-10-11 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inphinity_orm', '0020_auto_20181011_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bacteriophage',
            name='baltimore_classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baltimore_class', to='inphinity_orm.BaltimoreClassification'),
        ),
        migrations.AlterField(
            model_name='bacterium',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strain', to='inphinity_orm.Strain'),
        ),
    ]
