# Generated by Django 2.1.1 on 2018-10-11 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inphinity_orm', '0021_auto_20181011_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholeDNA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_db_online', models.TextField(null=True)),
                ('sequence_DNA', models.TextField()),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inphinity_orm.Organism')),
            ],
        ),
    ]
