# Generated by Django 2.1.1 on 2018-10-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inphinity_orm', '0022_wholedna'),
    ]

    operations = [
        migrations.AddField(
            model_name='contig',
            name='fasta_head',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='wholedna',
            name='fasta_head',
            field=models.TextField(null=True),
        ),
    ]
