# Generated by Django 2.1.1 on 2018-10-12 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inphinity_orm', '0023_auto_20181011_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bacteriophage',
            name='baltimore_classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baltimore_classification', to='inphinity_orm.BaltimoreClassification'),
        ),
        migrations.AlterField(
            model_name='bacterium',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bacteria', to='inphinity_orm.Strain'),
        ),
        migrations.AlterField(
            model_name='contig',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organism_contig', to='inphinity_orm.Organism'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organism_gene', to='inphinity_orm.Organism'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='contig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protein_contig', to='inphinity_orm.Contig'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protein_gene', to='inphinity_orm.Gene'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='position_end_contig',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='protein',
            name='position_start_contig',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='wholedna',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organism_wholeDNA', to='inphinity_orm.Organism'),
        ),
    ]
