# Generated by Django 2.1.1 on 2018-10-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inphinity_orm', '0025_auto_20181012_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='position_end_contig',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='position_start_contig',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
