# Generated by Django 2.1.1 on 2018-10-15 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inphinity_orm', '0028_auto_20181015_1315'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='domaininterationspair',
            unique_together={('domain_a', 'domain_b')},
        ),
    ]
