# Generated by Django 2.1.1 on 2018-10-16 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inphinity_orm', '0030_auto_20181016_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='COGInterationPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cog_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='COGSInterationPair_domainA', to='inphinity_orm.COG')),
                ('cog_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='COGSInterationPair_domainB', to='inphinity_orm.COG')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='coginterationspair',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='coginterationspair',
            name='cog_a',
        ),
        migrations.RemoveField(
            model_name='coginterationspair',
            name='cog_b',
        ),
        migrations.AlterField(
            model_name='cogsinteractionsource',
            name='cogs_interaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inphinity_orm.COGInterationPair'),
        ),
        migrations.AlterUniqueTogether(
            name='proteincog',
            unique_together={('protein', 'cog')},
        ),
        migrations.DeleteModel(
            name='COGInterationsPair',
        ),
        migrations.AlterUniqueTogether(
            name='coginterationpair',
            unique_together={('cog_a', 'cog_b')},
        ),
    ]
