# Generated by Django 2.1.1 on 2018-10-16 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inphinity_orm', '0031_auto_20181016_1322'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='COGSInteractionSource',
            new_name='COGInteractionSource',
        ),
    ]
