# Generated by Django 2.1.1 on 2018-10-16 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inphinity_orm', '0032_auto_20181016_1402'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coginteractionsource',
            unique_together={('cogs_interaction', 'information_source')},
        ),
    ]
