# Generated by Django 2.1.1 on 2018-10-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inphinity_orm', '0033_auto_20181016_1404'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PPICOGcore',
            new_name='PPICogScore',
        ),
    ]
