# Generated by Django 2.1.1 on 2018-10-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inphinity_orm', '0035_gene_position_of_gene'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gene',
            old_name='position_of_gene',
            new_name='number_of_seq',
        ),
    ]
