# Generated by Django 2.1.1 on 2018-10-26 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inphinity_orm', '0037_protein_organism'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protein_organism', to='inphinity_orm.Organism'),
        ),
    ]
