# Generated by Django 2.1.1 on 2018-10-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inphinity_orm', '0039_protein_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='accession_num',
            field=models.TextField(null=True),
        ),
    ]
