# Generated by Django 2.1.1 on 2018-11-01 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inphinity_orm', '0040_protein_accession_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protein',
            name='contig',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='position_end_contig',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='position_start_contig',
        ),
        migrations.AddField(
            model_name='gene',
            name='contig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gene_contig', to='inphinity_orm.Contig'),
        ),
        migrations.AddField(
            model_name='gene',
            name='position_end_contig',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gene',
            name='position_start_contig',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
