# Generated by Django 2.1.1 on 2018-11-11 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inphinity_orm', '0041_auto_20181101_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='acc_number',
            field=models.TextField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='gi_number',
            field=models.TextField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='gene',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protein_gene', to='inphinity_orm.Gene'),
        ),
    ]
