# Generated by Django 2.1.1 on 2018-11-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inphinity_orm', '0042_auto_20181111_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='acc_number',
            field=models.TextField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='gi_number',
            field=models.TextField(max_length=50, null=True, unique=True),
        ),
    ]
