# Generated by Django 2.1.1 on 2018-11-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inphinity_orm', '0044_gene_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='acc_number',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
